# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'app8' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app8
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Database', '~> 5.11.0'

end
